name: SURFdrive sync
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  workflow_dispatch:
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2.0.1
      - run: bun i
      - env:
          DLCS_CUSTOMER_ID: 7
          DLCS_API_KEY: ${{ secrets.DLCS_API_KEY }}
        run: bun run ./src/sync.ts the-berlage.json
                
            
