name: SURFdrive sync
run-name: Syncing SURFdrive folders with DLCS spaces
on:
  workflow_dispatch:
  schedule:
    - cron: "0 6-22 * * *"
jobs:
  sync:
    runs-on: ubuntu-latest
    env:
      DLCS_CUSTOMER_ID: 7
      DLCS_API_KEY: ${{ secrets.DLCS_API_KEY }}
    steps:
      - name: Checking out repository
        uses: actions/checkout@v4
      - name: Download, install, and setup Bun
        uses: oven-sh/setup-bun@v2.0.1
      - name: Install dependencies
        run: bun i
      - name: Run Maatwerk Sync
        run: bun run ./src/sync.ts maatwerk.json
      - name: Run Library Learning Centre Sync
        run: bun run ./src/sync.ts llc.json
      - name: Run Erfgoed Team sync
        run: bun run ./src/sync.ts erfgoed.json
